# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install requests
        pip install workbook
    - name: Run
      run: |
        python index.py
    - name: Send email
      uses: devellany/send-mail@v1.0.2
      with:
          host: smtp.naver.com
          account: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: yerim
          from: ${{secrets.MAIL_USERNAME}} 
          subject: Github Actions job result
          body: ''
          attachment : '[{"path":"Bestseller_Top50.csv"}]'
          to: ${{secrets.MAIL_USERNAME}}
    

