# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install requests
    - name: Run
      run: |
        python index.py
    - name: Send email
      uses: dawidd6/action-send-mail@v2.1.0
      with:
          server_address: smtp.naver.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          # Literal body:
          # body: Build job of ${{github.repository}} completed successfully!
          # Read file contents as body:
          body: file://20200403_Bestseller_Top50.xlsx
          to: ${{secrets.MAIL_USERNAME}}
          from: yerim # <${{secrets.MAIL_USERNAME}}>
          # Optional content type (defaults to text/plain):
          content_type: text/csv
